In [3]:
import numpy as np 

a = np.ones((4, 6))    # a is a (4, 6) 2d array
b = np.ones((4, 1))    # b is a (4, 1) 2d array
c = np.ones((1, 6))     # c is a (1, 6) 2d array
d = np.ones(6)          # d is a size-6 1d array

print(a.shape, "\n", a)

(4, 6) 
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [15]:
x = a[:, 0]
print(f"a[:, 0] = {x}, shape: {x.shape}")

print()


y = a[0, :]
print(f"a[0, :] = {y}, shape: {y.shape}")

a[:, 0] = [0. 0. 0. 0.], shape: (4,)

a[0, :] = [0. 0. 0. 0. 0. 0.], shape: (6,)


In [14]:
print(f"a, shape: {a.shape} \n {a}")
print()
x = a[:, 0:3]
print(f"a[:, 0:3], shape: {x.shape} \n {x}")

a, shape: (4, 6) 
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

a[:, 0:3], shape: (4, 3) 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
print(f"a, shape: {a.shape} \n {a}")
print()
x = a[None, :, :]
print(f"a[None, :, :], shape: {x.shape} \n {x}")

a, shape: (4, 6) 
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

a[None, :, :], shape: (1, 4, 6) 
 [[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


In [16]:
print(f"a, shape: {a.shape} \n {a}")
print()

# x.shape = (4, 1, 6)
x = a[:, None, :]
print(f"a[:, None, :], shape: {x.shape} \n {x}")

a, shape: (4, 6) 
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

a[:, None, :], shape: (4, 1, 6) 
 [[[0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]]]


In [20]:
a = np.ones((4, 6)) 
b = 2 * np.ones((4, 1)) 

print(f"a, shape: {a.shape} \n {a}")
print(f"b, shape: {b.shape} \n {b}")

print(f"a+b, shape: {(a+b).shape} \n {a+b}")

a, shape: (4, 6) 
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
b, shape: (4, 1) 
 [[2.]
 [2.]
 [2.]
 [2.]]
a+b, shape: (4, 6) 
 [[3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3.]]


In [21]:
a = np.ones((1, 6)) 
b = 2 * np.ones((4, 1)) 

print(f"a, shape: {a.shape} \n {a}")
print(f"b, shape: {b.shape} \n {b}")

print(f"a+b, shape: {(a+b).shape} \n {a+b}")

a, shape: (1, 6) 
 [[1. 1. 1. 1. 1. 1.]]
b, shape: (4, 1) 
 [[2.]
 [2.]
 [2.]
 [2.]]
a+b, shape: (4, 6) 
 [[3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3.]]


In [22]:
a = np.ones(6)
b = 2 * np.ones((4, 1)) 

print(f"a, shape: {a.shape} \n {a}")
print(f"b, shape: {b.shape} \n {b}")

print(f"a+b, shape: {(a+b).shape} \n {a+b}")

a, shape: (6,) 
 [1. 1. 1. 1. 1. 1.]
b, shape: (4, 1) 
 [[2.]
 [2.]
 [2.]
 [2.]]
a+b, shape: (4, 6) 
 [[3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3.]]


In [12]:
print(f"c, shape: {c.shape} \n {c}")
print(f"d, shape: {d.shape} \n {d}")

print(f"c+d: \n {c+d}")

c, shape: (6, 1) 
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
d, shape: (4,) 
 [1. 1. 1. 1.]
c+d: 
 [[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


In [11]:
c = np.ones((6, 1))
d = np.ones(4)

print(f"c, shape: {c.shape} \n {c}")
print(f"d, shape: {d.shape} \n {d}")
print(f"c+d: \n {c+d}")

c, shape: (6, 1) 
 [[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
d, shape: (4,) 
 [1. 1. 1. 1.]
c+d: 
 [[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
